### ISSUE TITLE
Issues giving policy to admin user

### ISSUE THREAD

**Issue by Mani-Siga** [microsoft/csapps-msteams-watercooler#30]
I'm following the exact steps as outlined in the deployment guide. When I try to give the policy to admin user from section 5, I run into an error.

```
PS /home/mani> New-CsApplicationAccessPolicy -Identity OnlineMeeting-WaterCooler -AppIds "5b3dadaa-0982-462a-8dab-xxxxxxxxx" -Description "Water cooler - Online meeting policy"
Get-CsOnlineSession: /usr/local/share/powershell/Modules/MicrosoftTeams/2.3.1/netcoreapp3.1/SfBORemotePowershellModule.psm1:63
Line |
  63 |      $remoteSession = & (Get-CsOnlineSessionCommand)
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Connecting to remote server
     | api.interfaces.records.teams.microsoft.com failed with the
     | following error message : Client did not get proper response from
     | server. For more information, see the about_Remote_Troubleshooting
     | Help topic.

Invoke-Command: /usr/local/share/powershell/Modules/MicrosoftTeams/2.3.1/netcoreapp3.1/SfBORemotePowershellModule.psm1:22959
 Line |
22959 |  …    -Session (Get-PSImplicitRemotingSession -CommandName 'New-CsApplic …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Cannot validate argument on parameter 'Session'. The argument is
      | null or empty. Provide an argument that is not null or empty, and
      | then try the command again.
```

I verified that the MSTeams module version is 2.3.1, and I have tried multiple accounts to see if this is really had to do with my access issues in the Org structure. It turns out others were facing similar issues, without any solution. 

This is blocking me from installing the application on my teams. Any help is appreciated.

**Comment by wildmanwild** [comment]
Does anybody have an answer for this issue please? I've followed the same steps set out, unfortunately each time  I receive the same error as if something has been depreciated or changed around the SfB online PowerShell.

**Comment by rdeoburman** [comment]
Try giving policy from admin account. Please make sure MSTeams modules are updated
