### ISSUE TITLE
App Service Deployment/Sync - 'react-scripts' is not recognized as an internal or external command,   operable program or batch file.

### ISSUE THREAD

**Issue by Xileize** [microsoft/csapps-msteams-watercooler#34]
Afternoon, I'm following the readme to deploy Watercooler and have created all of the app services etc in our Azure subscription. I have also published the app to Teams, and can add the app to my Teams with no issues.

However, when trying to open the app in Teams, I am just greeted with the default Microsoft "welcome to app development" type splash screen.

Going into the app service in Azure, I'm finding that the deployment/sync of the data from this External Git source is failing with the following error:

_'react-scripts' is not recognized as an internal or external command, operable program or batch file._

The readme shows no pre-requisite for needing to use the React framework, so I'm guessing that the files are possibly not being pulled from somewhere they should be, or I've missed some config step or something.

Any help would be greatly appreciated. Happy to provide further information if required.

Thanks.

**Comment by rdeoburman** [comment]
Hi Xileize, as I can understand the deployment is failed on app service. if you tried deployment on P1V2, you please try deploying on P2V2 service plan. Once deployment is successful on P2V2, you can change plan to P1V2.
