### ISSUE TITLE
Change the Name of the App "watercooler" of the welcome tour. 

### ISSUE THREAD

**Issue by laracloud123** [microsoft/csapps-msteams-watercooler#36]
Hello, 
I would like to rename the app. Therefor I want also change the name of the app in the welcome tour. Is that possible?

<img width="689" alt="Watercooler_Problem" src="https://user-images.githubusercontent.com/75142069/154272246-19f97888-efe4-4a1d-93a7-083caaed6691.png">

Thank you in advance :)

**Comment by joshjohnson90** [comment]
We had exactly the same question. I searched all over to find it. I wondered if it was stored as an image file, which could be photoshopped and replaced?? Will keep digging. Hoping someone from Microsoft will be able to offer us an answer!

**Comment by vdesetty** [comment]
Hi [laracloud123](https://github.com/laracloud123)/[Josh Johnson](https://github.com/joshjohnson90), Thanks for connecting.

As of now, its not configurable. But you can still change at app UI constants by download the code locally and manually deployed.

Code part to change:[csapps-msteams-watercooler/WaterCoolerConstants.ts at main · microsoft/csapps-msteams-watercooler (github.com)](https://github.com/microsoft/csapps-msteams-watercooler/blob/main/WaterCoolerAPI/WaterCoolerAPI/ClientApp/src/WaterCoolerConstants.ts)
![image](https://user-images.githubusercontent.com/79343420/155181757-be326a01-b6e3-43d6-9396-22de1f8a614b.png)

Manual deployment reference link:
https://docs.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=cli
